export const COUNTRY_LIST_REQUEST = 'COUNTRY_LIST_REQUEST';
export const COUNTRY_LIST_SUCCESS = 'COUNTRY_LIST_SUCCESS';
export const COUNTRY_LIST_FAIL = 'COUNTRY_LIST_FAIL';
export const COUNTRY_FILTER = 'COUNTRY_FILTER';
export const SET_QUERY = 'SET_QUERY';
export const CLEAR_QUERY = 'CLEAR_QUERY';
export const CLEAR_AFTER = 'CLEAR_AFTER';
export const LOAD_MORE = 'LOAD_MORE';
export const SET_SELECTED = 'SET_SELECTED';
export const CLEAR_SELECTED = 'CLEAR_SELECTED';

export const PER_PAGE = 25;
